spring.application.name=message-service
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:9000
server.port=8081

spring.grpc.client.default-channel.address=localhost:8083
spring.grpc.client.default-channel.secure=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-retries=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.retry.max-interval=10000ms

logging.level.org.springframework.security=INFO
