package org.example.botservice.service;

import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker;
import io.github.resilience4j.retry.annotation.Retry;
import lombok.extern.slf4j.Slf4j;
import org.example.botservice.domain.ChatMessage;
import org.example.botservice.domain.ChatSession;
import org.example.botservice.dto.ChatRequestDTO;
import org.example.botservice.dto.OpenRouterRequestDTO;
import org.example.botservice.dto.OpenRouterResponseDTO;
import org.example.botservice.exception.InvalidLLMResponseException;
import org.example.botservice.exception.RetryableHttpException;
import org.example.botservice.storage.ChatSessionStorage;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;

import java.util.ArrayList;
import java.util.List;

/**
 * Service class responsible for managing chat interactions with a Large Language Model (LLM).
 * This class handles the processing and storage of chat sessions, sending requests to the
 * LLM API, and managing fallback mechanisms in case of service unavailability.
 */
@Slf4j
@Service
public class ChatService {

    private final ChatSessionStorage chatSessionStorage;
    private final RestClient restClient;

    @Value("${openrouter.model}")
    private String model;

    public ChatService(ChatSessionStorage chatSessionStorage, RestClient restClient) {
        this.chatSessionStorage = chatSessionStorage;
        this.restClient = restClient;
    }



    /**
     * Handles the process of interacting with a Large Language Model (LLM) by sending user input and
     * contextual information, and receiving the model's response. The method also manages the storage
     * of chat history for the associated session, ensuring that each conversation is tracked effectively.
     *
     * @param dto an instance of {@link ChatRequestDTO} containing the session identifier, user message,
     *            and personality settings for the chat interaction.
     * @return the response generated by the LLM as a string.
     * @throws RetryableHttpException if the LLM service is unavailable or if circuit breaker fallback
     *                                is triggered.
     */
    public String chatWithLLM(ChatRequestDTO dto) {
        ChatSession chatSession = chatSessionStorage.getOrCreateChatSession(dto.sessionId());

        List<OpenRouterRequestDTO.Message> apiMessages = new ArrayList<>();
        apiMessages.add(new OpenRouterRequestDTO.Message("system", dto.personality().getSystemPrompt()));

        chatSession.getChatHistory().forEach(m ->
                apiMessages.add(new OpenRouterRequestDTO.Message(m.getRole(), m.getContent()))
        );

        apiMessages.add(new OpenRouterRequestDTO.Message("user", dto.message()));

        try {
            String content = fetchResponseFromLLM(apiMessages);
            // Only store in history if we got a real LLM response (not a circuit breaker fallback)
            chatSession.addMessage(new ChatMessage("user", dto.message(), "You"));
            chatSession.addMessage(new ChatMessage("assistant", content, dto.personality().toString()));
            return content;
        } catch (RetryableHttpException e) {
            // Circuit breaker is open or service unavailable - don't pollute history
            throw e;
        }

    }

    /**
     * Sends a list of formatted messages and model information to a Large Language Model (LLM)
     * API endpoint and retrieves the response, handling retries and circuit breaker mechanisms
     * for improved robustness in case of transient failures.
     *
     * @param apiMessages a list of {@link OpenRouterRequestDTO.Message} objects representing the
     *                    messages and contextual input to be sent to the LLM.
     * @return the content of the response message generated by the LLM as a string.
     * @throws RetryableHttpException if the LLM service returns a retryable HTTP status code (e.g., 429, 500).
     * @throws InvalidLLMResponseException if the LLM returns an invalid or empty response.
     */
    @CircuitBreaker(name = "chatService", fallbackMethod = "fallback")
    //Break stream of tries if too many failures, and call fallback method
    @Retry(name = "chatService") //Try again if fails, up to max-attempts
    public String fetchResponseFromLLM(List<OpenRouterRequestDTO.Message> apiMessages) {
        var openRouterRequest = new OpenRouterRequestDTO(model, apiMessages);

        OpenRouterResponseDTO result = restClient.post()
                .uri("/chat/completions")//Start of URI configured in RestClientConfiguration.java
                .body(openRouterRequest) //Send JSON body of messages and model
                .retrieve()
                .onStatus(s -> s.value() == 429 || s.value() == 500,
                        (req, resp) -> {
                            throw new RetryableHttpException(
                                    "Upstream LLM returned " + resp.getStatusCode().value()
                            );
                        })
                .body(OpenRouterResponseDTO.class);

        if (result == null || result.choices() == null || result.choices().isEmpty()) {
            throw new InvalidLLMResponseException(
                    "The Gods sent an empty omen (Invalid response from LLM)",
                    model,
                    HttpStatus.BAD_GATEWAY.value()
            );
        }
        return result.choices().getFirst().message().content();

    }

    /**
     * Handles the fallback mechanism for the circuit breaker. This method is triggered when
     * the circuit breaker is open, indicating that the dependent service is currently unavailable
     * or under excessive load. Logs the exception and throws a {@link RetryableHttpException} to
     * signal that the operation can be retried later.
     *
     * @param e the exception that caused the fallback to be triggered.
     * @return this method does not return a value as it always throws a {@link RetryableHttpException}.
     * @throws RetryableHttpException indicating that the upstream service is unavailable and the
     *                                operation should be retried at a later time.
     */
    public String fallback(Exception e) {
        // Circuit breaker is open - throw exception so it doesn't pollute chat history
        log.warn("Circuit breaker fallback triggered for LLM call. Cause: {}", e.getMessage(), e);
        throw new RetryableHttpException("The Gods are not responding - service temporarily unavailable"+ e.getMessage());
    }

    public ChatSession getSessionHistory(String sessionId) {
        return chatSessionStorage.getOrCreateChatSession(sessionId);
    }

    public void clearChatHistory(String sessionId) {
        chatSessionStorage.clearSessionHistory(sessionId);
    }

}
