package org.example.botservice.dto;

import java.util.List;

/**
 * A data transfer object representing a response from the OpenRouter API.
 * This DTO encapsulates the choices returned by the API, where each choice
 * contains a message representing a specific response.
 *
 * @param choices A list of choices provided in the response. Each choice contains
 *                a message with the content generated by the OpenRouter API.
 */
public record OpenRouterResponseDTO(List<Choice> choices) {
     public record Choice(Message message) {}
    public record Message(String content){}
}
